export const authenticationTypes = {
  AUTHENTICATION_REQUEST: 'AUTHENTICATION|AUTHENTICATION_REQUEST',
  AUTHENTICATION_SUCCESS: 'AUTHENTICATION|AUTHENTICATION_SUCCESS',
  AUTHENTICATION_ASYNC: 'AUTHENTICATION|AUTHENTICATION_ASYNC',

  REGISTER_REQUEST: 'AUTHENTICATION|REGISTER_REQUEST',
  REGISTER_FAILED: 'AUTHENTICATION|REGISTER_FAILED',
  REGISTER_SUCCESS: 'AUTHENTICATION|REGISTER_SUCCESS',
  REGISTER_ASYNC: 'AUTHENTICATION|REGISTER_ASYNC',

  CHECK_REQUEST: 'AUTHENTICATION|CHECK_REQUEST',
  CHECK_SUCCESS: 'AUTHENTICATION|CHECK_SUCCESS',
  CHECK_ASYNC: 'AUTHENTICATION|CHECK_ASYNC',

  LOGOUT_SUCCESS: 'AUTHENTICATION|LOGOUT_SUCCESS',
  LOGOUT_ASYNC: 'AUTHENTICATION|LOGOUT_ASYNC',
};
